language: php

sudo: false

php:
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update --no-interaction --no-suggest --no-progress

script:
    - php vendor/bin/phing
